### ISSUE TITLE
io.seata.rm.tcc.interceptor.ActionInterceptorHandler 126 : TCC branch Register error

### ISSUE THREAD

**Issue by alileohe** [seata/seata#1734] opened 2019-10-09 09:18 UTC
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
线上出现大量io.seata.rm.tcc.interceptor.ActionInterceptorHandler 126 : TCC branch Register error, xid:10.35.226.31:8091:2016957836 io.seata.core.exception.TransactionException异常，并且发现里面的xid是一样的

1、经过排查发现异常是注册分支事务检查全局事务不存在
class：io.seata.server.coordinator.DefaultCore
    private GlobalSession assertGlobalSessionNotNull(String xid) throws TransactionException {
        GlobalSession globalSession = SessionHolder.findGlobalSession(xid);
        if (globalSession == null) {
            throw new TransactionException(TransactionExceptionCode.GlobalTransactionNotExist, "" + xid + "");
        }
        return globalSession;
    }

 2、经过排查发现xid:10.35.226.31:8091:2016957836事务已经回滚，所以全局事务表和分支事务表相关记录已经删除
 3、查询日志发现该笔事务提交时出现超时，导致RootContext.unbind()没被调用，xid没被清除

class：io.seata.tm.api.DefaultGlobalTransaction
    public void commit() throws TransactionException {
        if (role == GlobalTransactionRole.Participant) {
            // Participant has no responsibility of committing
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("Ignore Commit(): just involved in global transaction [" + xid + "]");
            }
            return;
        }
        if (xid == null) {
            throw new IllegalStateException();
        }

        status = transactionManager.commit(xid);
        if (RootContext.getXID() != null) {
            if (xid.equals(RootContext.getXID())) {
                RootContext.unbind();
            }
        }
        if (LOGGER.isInfoEnabled()) {
            LOGGER.info("[" + xid + "] commit status:" + status);
        }

    }

    4、导致新的事务开启时，使用了原来没被清除的全局事务id
   class： io.seata.tm.api.TransactionalTemplate
     
   public Object execute(TransactionalExecutor business) throws Throwable {
        // 1. get or create a transaction
        GlobalTransaction tx = GlobalTransactionContext.getCurrentOrCreate();

        // 1.1 get transactionInfo
        TransactionInfo txInfo = business.getTransactionInfo();
        if (txInfo == null) {
            throw new ShouldNeverHappenException("transactionInfo does not exist");
        }
        try {

            // 2. begin transaction
            beginTransaction(txInfo, tx);

            Object rs = null;
            try {

                // Do Your Business
                rs = business.execute();

            } catch (Throwable ex) {

                // 3.the needed business exception to rollback.
                completeTransactionAfterThrowing(txInfo,tx,ex);
                throw ex;
            }

            // 4. everything is fine, commit.
            commitTransaction(tx);

            return rs;
        } finally {
            //5. clear
            triggerAfterCompletion();
            cleanUp();
        }
    }

class：io.seata.tm.api.GlobalTransactionContext
    /**
     * Get GlobalTransaction instance bind on current thread.
     *
     * @return null if no transaction context there.
     */
    private static GlobalTransaction getCurrent() {
        String xid = RootContext.getXID();
        if (xid == null) {
            return null;
        }
        return new DefaultGlobalTransaction(xid, GlobalStatus.Begin, GlobalTransactionRole.Participant);
    }

    /**
     * Get GlobalTransaction instance bind on current thread. Create a new on if no existing there.
     *
     * @return new context if no existing there.
     */
    public static GlobalTransaction getCurrentOrCreate() {
        GlobalTransaction tx = getCurrent();
        if (tx == null) {
            return createNew();
        }
        return tx;
    }

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2019-10-08 23:20:00.591 ERROR 133262 [pool-40-thread-2] io.seata.rm.tcc.interceptor.ActionInterceptorHandler 126 : TCC branch Register error, xid:10.35.226.31:8091:2016957836 io.seata.core.exception.TransactionException: Response[TransactionException[10.35.226.31:8091:2016957836]] at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:68) ~[seata-rm-0.6.1-FIN-SNAPSHOT.jar!/:?] at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96) ~[seata-rm-0.6.1-FIN-SNAPSHOT.jar!/:?] at io.seata.rm.tcc.interceptor.ActionInterceptorHandler.doTccActionLogStore(ActionInterceptorHandler.java:121) ~[seata-tcc-0.6.1-FIN-SNAPSHOT.jar!/:?] at io.seata.rm.tcc.interceptor.ActionInterceptorHandler.proceed(ActionInterceptorHandler.java:72) ~[seata-tcc-0.6.1-FIN-SNAPSHOT.jar!/:?] at io.seata.spring.tcc.TccActionInterceptor.invoke(TccActionInterceptor.java:78) ~[seata-spring-0.6.1-FIN-SNAPSHOT.jar!/:?] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at com.sun.proxy.$Proxy142.chargeInterest(Unknown Source) ~[?:?] at com.oppo.accountingsuppl.core.historydata.AccountHandler.chargeInterest(AccountHandler.java:557) ~[accounting-suppl-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT] at com.oppo.accountingsuppl.core.historydata.AccountHandler.tallyTrans(AccountHandler.java:239) ~[accounting-suppl-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT] at com.oppo.accountingsuppl.core.historydata.AccountHandler$$FastClassBySpringCGLIB$$57eb3f42.invoke() ~[accounting-suppl-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:106) ~[seata-spring-0.6.1-FIN-SNAPSHOT.jar!/:?] at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:64) ~[seata-tm-0.6.1-FIN-SNAPSHOT.jar!/:?] at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:103) ~[seata-spring-0.6.1-FIN-SNAPSHOT.jar!/:?] at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:78) ~[seata-spring-0.6.1-FIN-SNAPSHOT.jar!/:?] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at com.oppo.accountingsuppl.core.historydata.AccountHandler$$EnhancerBySpringCGLIB$$34850f3b.tallyTrans() ~[accounting-suppl-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT] at com.oppo.accountingsuppl.core.historydata.HistoryDataServiceImpl$1$1.doInTransactionWithoutResult(HistoryDataServiceImpl.java:142) ~[accounting-suppl-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT] at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36) ~[spring-tx-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.1.2.RELEASE.jar!/:5.1.2.RELEASE] at com.oppo.accountingsuppl.core.historydata.HistoryDataServiceImpl$1.run(HistoryDataServiceImpl.java:139) ~[accounting-suppl-core-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_192] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_192] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment] 2019-10-09 13:35
@alileohe Thank you very much for your feedback. The cause of the problem has been found and the problem will be fixed soon.

**Closed** 2019-10-10 02:39 UTC
Labels: area/TCC, kind/bug
