### ISSUE TITLE
primary key is of type bigint, Branch transactions cannot be rollback

### ISSUE THREAD

**Issue by wuyou0922** [seata/seata#1184] opened 2019-06-10 03:19 UTC
场景：
       A服务调用B服务。  B服务对B表在新增操作 ，A服务调用完B服务后主动抛异常，B服务回滚。但因为B表的主键类型为bigint，导致B分支事务回滚失败。
分析:
      根据代码追踪，在B服务执行回滚操作时，会根据undo_log表检查需要回滚的数据是否被脏读。会有before，after副本。原因是获取before,after副本的序列化方式不一样。导致数据类型不一致。被程序认为该数据已经被脏读。
before序列化方式：JSONBasedUndoLogParser.decode ,bigint转成了Integer(错误)
![image](https://user-images.githubusercontent.com/16377153/59170240-53cc3280-8b70-11e9-9258-40063e51df1a.png)
![1](https://user-images.githubusercontent.com/16377153/59170315-90982980-8b70-11e9-8912-043a8eeae4a0.png)
after序列化方式：AbstractUndoExecutor.queryCurrentRecords>>>TableRecords.buildRecords ,bigint转成了Long(正确)
![2](https://user-images.githubusercontent.com/16377153/59170474-64c97380-8b71-11e9-9746-6753f3fd4fea.png)
注：官方用例没有这个问题。因为操作的业务表的数据库主键类型为int。

**Comment by xingfudeshi** [comment] 2019-06-10 05:00
Thanks for reporting,Could you submit a PR to improve this?

**Comment by slievrly** [comment] 2019-07-01 06:42
@wuyou0922 The pr you mentioned is compatible with this problem. I think the key to the problem is why the metadata type of TableMeta is wrong.

**Comment by l81893521** [comment] 2020-07-09 03:03
This issue might had been fix. So, I will close this issue, if you found any other problem, hope you can report us.

**Closed by l81893521** 2020-07-09 03:03 UTC
Labels: kind/bug
