### ISSUE TITLE
sample doesn’t work

### ISSUE THREAD

**Issue by baozou66** [seata/seata#380] opened 2019-02-11 09:52 UTC
其他都起来了，运行business报错，没注册上么？我用的是默认的注册中心multicast。

Exception in thread "main" org.apache.dubbo.rpc.RpcException: Failed to invoke the method deduct in the service com.alibaba.fescar.tm.dubbo.StorageService. No provider available for the service com.alibaba.fescar.tm.dubbo.StorageService from registry 224.5.6.7:1234 on the consumer 192.168.109.1 using the dubbo version 2.7.0. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:265)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:57)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:241)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57)
	at org.apache.dubbo.common.bytecode.proxy1.deduct(proxy1.java)
	at com.alibaba.fescar.tm.dubbo.impl.BusinessServiceImpl.purchase(BusinessServiceImpl.java:46)
	at com.alibaba.fescar.tm.dubbo.impl.BusinessServiceImpl$$FastClassBySpringCGLIB$$9dbefa1d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at com.alibaba.fescar.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:64)
	at com.alibaba.fescar.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:52)
	at com.alibaba.fescar.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
	at com.alibaba.fescar.tm.dubbo.impl.BusinessServiceImpl$$EnhancerBySpringCGLIB$$1c1318d7.purchase(<generated>)
	at com.alibaba.fescar.tm.dubbo.impl.BusinessServiceImpl.main(BusinessServiceImpl.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
---------------------

**Comment by xuhongda** [comment] 2019-02-13 08:31
我也遇到dubbomulticast模式无法调用的情况，可以注释掉multicast，将下面的 <dubbo:registry address="zookeeper://localhost:2181"/>放开：

    ```

> <dubbo:application name="dubbo-demo-account-service"  />
>     <!--<dubbo:registry address="multicast://224.5.6.7:1234?unicast=false" />-->
>     <!--support zk-->
>     <dubbo:registry address="zookeeper://localhost:2181"/>

```

**Comment by xingfudeshi** [comment] 2019-02-17 08:36
It seems the provider(dubbo service) doesn't register to registry properly.can you provide a full demo that can reproduce this problem?thanks.

**Comment by snailshen2014** [comment] 2019-02-20 03:44
用zk 做为dubbo register

**Comment by leizhiyuan** [comment] 2019-05-16 23:15
as everyone above said，you can use nacos or zk for test.

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one

**Closed by leizhiyuan** 2019-05-16 23:15 UTC
