### ISSUE TITLE
Build failure : Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:flatten-maven-plugin:1.1.0:flatten

### ISSUE THREAD

**Issue by chenliwei2016** [seata/seata#1019] opened 2019-05-12 10:20 UTC
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:flatten-maven-plugin:1.1.0:flatten (execution: flatten, phase: process-resources)

Build error after downloading source code and import to eclipse and the building failed, please help

**Comment by leizhiyuan** [comment] 2019-05-13 03:41
can you run this command in console，

```
mvn clean install -Dmaven.test.skip=true
```

and provide the detail info?

**Comment by xingfudeshi** [comment] 2019-05-22 00:35
This problem should be fixed.i will close this issue,if you have further question,please be free to post here.

**Comment by xingfudeshi** [comment] 2019-05-22 00:35
This problem should be fixed.i will close this issue,if you have further question,please be free to post here.

**Closed by xingfudeshi** 2019-05-22 00:35 UTC
Labels: kind/bug

**Comment by chenliwei2016** [comment] 2019-05-22 02:11
Thank your all for the reply, I just git pull the latest code, and re-import the maven project into my spring tools suite 3.9.4, it prompts the below error, maybe is it a sts version problem?

<img width="628" alt="image" src="https://user-images.githubusercontent.com/25098175/58142419-8671c200-7c79-11e9-8288-0ea6694099e2.png">

**Comment by chenliwei2016** [comment] 2019-05-22 02:13
By the way, this problem cannot happen if I choose IntelliJ IDEA 14.

**Comment by chenliwei2016** [comment] 2019-05-22 02:14
@xingfudeshi @leizhiyuan

**Comment by chenliwei2016** [comment] 2019-05-22 14:15
@xingfudeshi You simply said 'the problem should be fixed' means it was fixed already? or it will be fixed in the following version?

please provide the solution if you mean this issue was fixed already. it will help the others who met the same problem with mine.

**Comment by xingfudeshi** [comment] 2019-05-22 22:17
Sorry.I was working.
Have you tried to build seata on command line?try the following commands:
mvn clean install -DskipTests=true -U

**Comment by xingfudeshi** [comment] 2019-05-22 22:26
If you can build seata on the command line, this is not a bug and you can ignore it.In fact, we build seata every day, and if we find a problem that prevents a build, we will fix it directly.
